language: php
php:
  - '7.2'

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs --standard=vendor/yiisoft/yii2-coding-standards/Yii2 --extensions=php --ignore=vendor,tests .
  - vendor/bin/codecept run unit,soap